name: CI/CD with Documentation Generation

on:
  push:
    branches:
      - master # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1 # Adjust to your PHP version
    
    - name: Generate Documentation
      run: |
        wget https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.4.1/phpDocumentor.phar
        php phpDocumentor.phar -d . -t ./docs

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        
    - name: Check for Documentation Changes & Status
      run: |
        # Check if there are changes in the docs directory
        if [ -n "$(git status --porcelain docs)" ]; then
          echo "Documentation changes detected. Committing and pushing."
          git add ./docs
          git commit -m "Update documentation"
          git push
        else
          echo "Documentation is up to date. No changes to commit."
        fi
