name: Psalm Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '35 8 * * 2'

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Use the PHP version you need
          tools: composer:v2 # Install Composer version 2
          
      - name: Install Psalm
        run: |
          composer global require "vimeo/psalm"
          echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Initialize Psalm
        run: |
          psalm --init source_folder

      - name: Psalm Security Scan
        uses: psalm/psalm-github-security-scan@f3e6fd9432bc3e44aec078572677ce9d2ef9c287

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
