name: PHP CI/CD with Security Scanning

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1 # Choose your desired PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHP_CodeSniffer
        run: composer phpcs

      - name: Run PHPStan
        run: composer phpstan

      - name: Security Scanning
        run: |
          composer require sensiolabs/security-checker --dev
          php vendor/bin/security-checker security:check

      - name: Publish Code Analysis Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: code-analysis-results
          path: |
            phpcs.xml
            phpstan.neon
            security-checker-report.txt
